# Generated by Django 5.0.6 on 2024-06-29 19:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[("first", "First Time"), ("return", "Return")],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendig", "Pendig"),
                            ("done", "Done"),
                            ("cancled", "Cancled"),
                        ],
                        default="pendig",
                        max_length=10,
                    ),
                ),
                ("pstatus", models.BooleanField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.TextField(max_length=50)),
                ("make", models.TextField(max_length=50)),
                (
                    "plate",
                    models.CharField(
                        max_length=9,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Plate number needd to be formated like AAA 000 A",
                                regex="^[A-Z]{3} [0-9]{3} [A-Z]$",
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Center",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("location", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("portable", "Portable")],
                        max_length=50,
                    ),
                ),
                (
                    "operating_hours",
                    models.CharField(
                        choices=[
                            ("9:00 AM - 5:00 AM", "9:00 AM - 5:00 PM"),
                            ("10:00 AM - 5:00 AM", "10:00 AM - 5:00 PM"),
                        ],
                        max_length=50,
                    ),
                ),
                ("number_of_slots_per_day", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Admin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="type",
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=13,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+250999999999'. Up to 12 digits allowed.",
                        regex="^\\+250\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("OWNER", "Owner"), ("ADMIN", "Admin")],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="owner_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="owner_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="car_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="App.car"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="center_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="App.center"
            ),
        ),
    ]
