# Generated by Django 5.0.6 on 2024-07-01 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_appointment_car_center_delete_admin_remove_user_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="center",
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.BooleanField()),
                ("recomendations", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="App.appointment",
                    ),
                ),
            ],
        ),
    ]
